### ISSUE TITLE
Can you provide the 77.3 mAP ResNet50 baseline

### ISSUE THREAD

**Issue by dreamerlin** [Qualcomm-AI-research/FrameExit#3]
Hi, thanks for your awesome work! 

I notice that FrameExit uses a ResNet50 with ImageNet pretrained and 10-frames training, achieving 77.3 mAP. That is a good performance. I tried to port the weight of `backbone`, `mlp`, and `classifier.0` (or `classifier.9`) of [activitynet_checkpoint_25gmac.pth](https://github.com/Qualcomm-AI-research/FrameExit/releases/download/v1.0/activitynet_checkpoint_25gmac.pth) to serve as the baseline classifier for me ,since they are trained first in your paper but failed ...

so could you please provide the baseline checkpoint for me? That would be great if you can give me a hand!

**Comment by aghodrati** [comment]
Hi dreamerlin, the pretrained weights for the backbone (Resnet-50) and heads are all in [activitynet_checkpoint_25gmac.pth](https://github.com/Qualcomm-AI-research/FrameExit/releases/download/v1.0/activitynet_checkpoint_25gmac.pth). Please note that the backbone is fine-tuned (i.e. you can't use Imagenet pretrained weights). Let me know if you need anything else.
