### ISSUE TITLE
Missing .config files for activitynet and kinetics

### ISSUE THREAD

**Issue by alexandrosstergiou** [Qualcomm-AI-research/FrameExit#4]
Hi,

Thank you for your interesting work!

I have noticed that some files in both [`activitynet_inference_2d.yml`](https://github.com/Qualcomm-AI-research/FrameExit/blob/main/config/activitynet_inference_2d.yml) and [`mini_kinetics_inference_2d.yml`](https://github.com/Qualcomm-AI-research/FrameExit/blob/main/config/minikinetics_inference_2d.yml) are missing.

Specifically, can you provide:
for `activitynet_inference_2d.yml`:
- `split_val_v1.3.txt`
- `classes.txt`

for `mini_kinetics_inference_2d.yml`:
- `split_val_minikinetics.txt`
- `kinetics_val.csv` (Unless if you are using [`s9xie/Mini-Kinetics-200/blob/master/val_ytid_list.txt`](https://github.com/s9xie/Mini-Kinetics-200/blob/master/val_ytid_list.txt) ?)
- `minik_classInd.txt` (Unless you are using AdaFuse's IDs [`mengyuest/AdaFuse/blob/master/data/kinetics/minik_classInd.txt`](https://github.com/mengyuest/AdaFuse/blob/master/data/kinetics/minik_classInd.txt) which correspond to a different set of labels than those in Mini-Kinetics-200.

**Comment by dreamerlin** [comment]
https://github.com/Qualcomm-AI-research/FrameExit/blob/main/inference.py#L17-L72
